CREATE TABLE Billett
(
    id INTEGER AUTO_INCREMENT NOT NULL,
    choose VARCHAR(255) NOT NULL,
    amount VARCHAR(255) NOT NULL,
    fname VARCHAR(255) NOT NULL,
    lname VARCHAR(255) NOT NULL,
    tel VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);